### ISSUE TITLE
vanilla chat failing with Internal Server error 

### ISSUE THREAD

**Issue by m-adams** [i-dot-ai/redbox-copilot#476]
**Describe the bug**
If you try and test vanilla chat e.g. on the Try It Now it failes with a 500
Looking at the logs you get an error about AI message not having a text attribute. It looks like it neeeds to use the content attribute.
**To Reproduce**
1. Go to '/vanilla'
2. Click on 'Try It Now'
3. Scroll down to '...Execute'

**Expected behavior**
It should respond with the response

**Comment by gecBurton** [comment]
thanks for fixing this @m-adams :)
